import Head from "next/head";
import Image from "next/image";
import { StubNavbar } from "../components/specific/StubNavbar";

// import { Valid } from "../components/Validation";
// import { List, ListItem } from "../components/List";
import { MainGrid, SideCol, ContentCol } from "../components/LayoutA";
import { FilePicker } from "../components/FilePicker";
// import NavDropDownItem from '../components/NavBar/NavDropDownItem'
// import Alert from "../components/Alert";
import { Card } from "../components/Card";
import { Button } from "../components/Button";
// import { useState } from "react";
// import styles from '../styles/Home.module.css'

export default function Playground(): any {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StubNavbar />

      <MainGrid>
        <SideCol>
          <Card />
        </SideCol>
        <ContentCol>
          <canvas className="border border-primary col-md-11 float-md-start ms-md-3" />
          <p>hi</p>
          <FilePicker
            fileCallback={() => {
              console.log("hi");
            }}
          />
          <Button label={"ha"} onClick={undefined} />
        </ContentCol>
        <footer className="footer">
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className="logo">
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </MainGrid>
    </>
  );
}
