import Head from "next/head";
import Image from "next/image";
import {
  NavBar,
  NavLogo,
  NavItem,
  NavDropDown,
  NavDropDownItem,
  NavDropDownDivider,
  NavSearch,
} from "../components/Navbar";

import { Valid } from "../components/Validation";
import { List, ListItem } from "../components/List";

// import NavDropDownItem from '../components/NavBar/NavDropDownItem'
import Alert from "../components/Alert";
// import { useState } from "react";
// import styles from '../styles/Home.module.css'

export default function Playground(): any {
  return (
    <>
      <NavBar
        logo={
          <NavLogo
            src="https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/atom.svg"
            label="HI"
          />
        }
      >
        <NavItem label="GoHere" link="#" />
        <NavItem label="Example" link="#" />
        <NavDropDown label="DropDown" link="#">
          <NavDropDownItem href={""} label={"AJ"} />
          <NavDropDownDivider />
          <NavDropDownItem href={""} label={"AGJ"} />
          <NavDropDownItem href={""} label={"FGAJ"} />
        </NavDropDown>
        <NavSearch />
      </NavBar>
      <div className="container">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="main">
          <div className="container">
            <div className="row">
              <div className="col">
                <input type="text" onChange={() => console.log("d")}></input>
              </div>
              <div className="col">
                <button
                  className="border border-primary"
                  onClick={() => console.log("d")}
                >
                  GET SOME
                </button>
              </div>
              <button onClick={(x) => console.log(() => console.log("d"))}>
                current shit
              </button>
              <button onClick={() => console.log("d")}>GET PROFILE</button>
            </div>
            <List>
              <ListItem key={"1"} label={"AHHH"} />
            </List>
            <div className="row">
              <ul>
                <li key="3">hi</li>
              </ul>
              <Valid label={"hi"} valid={true} />
            </div>
            <input
              type="text"
              className="form-control is-invalid"
              id="validationServer05"
              aria-describedby="validationServer05Feedback"
              required
            />
            <h1>
              Example heading <span className="badge bg-secondary">New</span>
            </h1>
            <Alert color="primary" />
          </div>
        </main>

        <footer className="footer">
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className="logo">
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
}
